# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-10 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20181206_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.DateTimeField()),
                ('logistics_company', models.IntegerField(choices=[(0, '圆通快递'), (1, '申通快递'), (2, '中通快递'), (3, '顺丰快递'), (4, 'EMS'), (5, '宅急送')], default=0, verbose_name='物流公司')),
                ('express_number', models.IntegerField(verbose_name='快递编号')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=200, verbose_name='物流信息')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('logist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Logistics')),
            ],
        ),
    ]
