# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-10 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_logistics_logisticsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='express_number',
            field=models.CharField(max_length=200, verbose_name='快递编号'),
        ),
    ]
