# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-24 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20181210_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistics',
            name='express_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='快递编号'),
        ),
    ]
